<?php

namespace backend\modules\end_user\home\controllers;

use backend\modules\end_user\home\models\Slider;
use yii\db\Query;
use yii\web\Controller;

class SiteController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $this->view->title = "Trang Chủ";
        $sliders = Slider::find()->limit(10)->active()->all();
        return $this->render("index", compact("sliders"));
    }
}