<?php

namespace backend\modules\end_user\home\controllers;

use yii\web\Controller;

class SiteController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->render("index");
    }
}