<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "administrative_regions".
 *
 * @property integer $id
 * @property string $name
 * @property string $name_en
 * @property string $code_name
 * @property string $code_name_en
 * @property string $aliasModel
 */
abstract class AdministrativeRegion extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'administrative_regions';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'name', 'name_en'], 'required'],
            [['id'], 'integer'],
            [['name', 'name_en', 'code_name', 'code_name_en'], 'string', 'max' => 255],
            [['id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'name_en' => 'Name En',
            'code_name' => 'Code Name',
            'code_name_en' => 'Code Name En',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\AdministrativeRegionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\AdministrativeRegionQuery(get_called_class());
    }


}
