<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "banner".
 *
 * @property integer $id
 * @property string $title
 * @property string $url
 * @property string $description
 * @property integer $status
 * @property string $type
 * @property integer $priority
 * @property string $created_at
 * @property string $updated_at
 * @property string $video_url
 * @property string $link
 * @property string $aliasModel
 */
abstract class Banner extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'banner';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['url', 'description', 'video_url', 'link'], 'string'],
            [['status', 'priority'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['title'], 'string', 'max' => 256],
            [['type'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'url' => 'Url',
            'description' => 'Description',
            'status' => 'Status',
            'type' => 'Type',
            'priority' => 'Priority',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'video_url' => 'Video Url',
            'link' => 'Link',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\BannerQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\BannerQuery(get_called_class());
    }


}
