<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "category".
 *
 * @property integer $id
 * @property string $name
 * @property string $type
 * @property string $code
 * @property string $icon
 * @property string $images
 * @property string $color
 * @property integer $priority
 * @property string $description
 * @property integer $parent_id
 * @property integer $owner_id
 * @property string $group_id
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $status
 * @property string $slug
 * @property string $aliasModel
 */
abstract class Category extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['icon', 'images', 'description', 'group_id'], 'string'],
            [['priority', 'parent_id', 'owner_id', 'status'], 'integer'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['name'], 'string', 'max' => 256],
            [['type'], 'string', 'max' => 32],
            [['code'], 'string', 'max' => 64],
            [['color'], 'string', 'max' => 10],
            [['slug'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'type' => 'Type',
            'code' => 'Code',
            'icon' => 'Icon',
            'images' => 'Images',
            'color' => 'Color',
            'priority' => 'Priority',
            'description' => 'Description',
            'parent_id' => 'Parent ID',
            'owner_id' => 'Owner ID',
            'group_id' => 'Group ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'status' => 'Status',
            'slug' => 'Slug',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\CategoryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\CategoryQuery(get_called_class());
    }


}
