<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "color".
 *
 * @property integer $id
 * @property string $name
 * @property string $value
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $delete_at
 * @property string $aliasModel
 */
abstract class Color extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'color';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'value'], 'string'],
            [['status'], 'integer'],
            [['created_at', 'updated_at', 'delete_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'value' => 'Value',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'delete_at' => 'Delete At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\ColorQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\ColorQuery(get_called_class());
    }


}
