<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "comment".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $status
 * @property integer $rating
 * @property string $title
 * @property string $content
 * @property string $images
 * @property integer $parent_id
 * @property integer $options_id
 * @property integer $module_id
 * @property string $type
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property string $aliasModel
 */
abstract class Comment extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'comment';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'status', 'rating', 'parent_id', 'options_id', 'module_id'], 'integer'],
            [['content'], 'string'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['title', 'images'], 'string', 'max' => 255],
            [['type'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'status' => 'Status',
            'rating' => 'Rating',
            'title' => 'Title',
            'content' => 'Content',
            'images' => 'Images',
            'parent_id' => 'Parent ID',
            'options_id' => 'Options ID',
            'module_id' => 'Module ID',
            'type' => 'Type',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\CommentQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\CommentQuery(get_called_class());
    }


}
