<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "contact".
 *
 * @property integer $id
 * @property integer $unique_external_id
 * @property string $first_name
 * @property string $last_name
 * @property string $name
 * @property string $description
 * @property string $note
 * @property string $phone
 * @property string $email
 * @property string $type
 * @property string $postal_code
 * @property string $time_zone
 * @property string $address_1
 * @property string $address_2
 * @property string $country
 * @property string $state
 * @property string $city
 * @property string $avatar
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $status
 * @property string $aliasModel
 */
abstract class Contact extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'contact';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['unique_external_id', 'status'], 'integer'],
            [['description', 'note', 'avatar'], 'string'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['first_name', 'last_name', 'name', 'phone', 'email', 'type', 'postal_code'], 'string', 'max' => 255],
            [['time_zone', 'address_1', 'address_2', 'country', 'state', 'city'], 'string', 'max' => 512]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'unique_external_id' => 'Unique External ID',
            'first_name' => 'First Name',
            'last_name' => 'Last Name',
            'name' => 'Name',
            'description' => 'Description',
            'note' => 'Note',
            'phone' => 'Phone',
            'email' => 'Email',
            'type' => 'Type',
            'postal_code' => 'Postal Code',
            'time_zone' => 'Time Zone',
            'address_1' => 'Address  1',
            'address_2' => 'Address  2',
            'country' => 'Country',
            'state' => 'State',
            'city' => 'City',
            'avatar' => 'Avatar',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'status' => 'Status',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\ContactQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\ContactQuery(get_called_class());
    }


}
