<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "customer".
 *
 * @property integer $id
 * @property integer $unique_external_id
 * @property integer $owner_id
 * @property string $name
 * @property string $description
 * @property string $note
 * @property string $phone
 * @property string $biz_phone
 * @property string $email
 * @property string $website
 * @property string $type
 * @property string $postal_code
 * @property string $time_zone
 * @property string $address_1
 * @property string $address_2
 * @property string $country
 * @property string $province_code
 * @property string $district_code
 * @property string $ward_code
 * @property string $avatar
 * @property string $custom_fields
 * @property string $additional_information
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property string $renewal_date
 * @property integer $status
 * @property string $groups
 * @property string $currency
 * @property string $language
 * @property string $code
 * @property string $aliasModel
 */
abstract class Customer extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'customer';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['unique_external_id', 'owner_id', 'status'], 'integer'],
            [['description', 'note', 'avatar', 'custom_fields', 'additional_information', 'groups'], 'string'],
            [['created_at', 'updated_at', 'deleted_at', 'renewal_date'], 'safe'],
            [['name', 'phone', 'biz_phone', 'email', 'website', 'type', 'postal_code', 'ward_code', 'currency', 'language', 'code'], 'string', 'max' => 255],
            [['time_zone', 'address_1', 'address_2', 'country', 'province_code', 'district_code'], 'string', 'max' => 512]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'unique_external_id' => 'Unique External ID',
            'owner_id' => 'Owner ID',
            'name' => 'Name',
            'description' => 'Description',
            'note' => 'Note',
            'phone' => 'Phone',
            'biz_phone' => 'Biz Phone',
            'email' => 'Email',
            'website' => 'Website',
            'type' => 'Type',
            'postal_code' => 'Postal Code',
            'time_zone' => 'Time Zone',
            'address_1' => 'Address  1',
            'address_2' => 'Address  2',
            'country' => 'Country',
            'province_code' => 'Province Code',
            'district_code' => 'District Code',
            'ward_code' => 'Ward Code',
            'avatar' => 'Avatar',
            'custom_fields' => 'Custom Fields',
            'additional_information' => 'Additional Information',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'renewal_date' => 'Renewal Date',
            'status' => 'Status',
            'groups' => 'Groups',
            'currency' => 'Currency',
            'language' => 'Language',
            'code' => 'Code',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\CustomerQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\CustomerQuery(get_called_class());
    }


}
