<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "department".
 *
 * @property integer $id
 * @property integer $office_id
 * @property integer $user_id
 * @property string $name
 * @property string $description
 * @property string $custom_fields
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $status
 * @property string $additional_information
 * @property string $aliasModel
 */
abstract class Department extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'department';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['office_id', 'user_id', 'status'], 'integer'],
            [['custom_fields', 'additional_information'], 'string'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['name'], 'string', 'max' => 255],
            [['description'], 'string', 'max' => 512]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'office_id' => 'Office ID',
            'user_id' => 'User ID',
            'name' => 'Name',
            'description' => 'Description',
            'custom_fields' => 'Custom Fields',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'status' => 'Status',
            'additional_information' => 'Additional Information',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'id' => 'ID',
            'office_id' => 'Office ID',
            'user_id' => 'Deparment Head ID',
            'name' => 'Name of the Department',
            'description' => 'Description of the Department',
            'custom_fields' => 'Custom field',
        ]);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\DepartmentQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\DepartmentQuery(get_called_class());
    }


}
