<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "discount_code".
 *
 * @property integer $id
 * @property string $product_ids
 * @property string $code
 * @property integer $price
 * @property string $description
 * @property string $reason
 * @property integer $limit
 * @property integer $status
 * @property string $expired_at
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property string $aliasModel
 */
abstract class DiscountCode extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'discount_code';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['price', 'limit', 'status'], 'integer'],
            [['description'], 'string'],
            [['expired_at', 'created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['product_ids', 'code', 'reason'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'product_ids' => 'Product Ids',
            'code' => 'Code',
            'price' => 'Price',
            'description' => 'Description',
            'reason' => 'Reason',
            'limit' => 'Limit',
            'status' => 'Status',
            'expired_at' => 'Expired At',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\DiscountCodeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\DiscountCodeQuery(get_called_class());
    }


}
