<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "file_storage_item".
 *
 * @property integer $id
 * @property string $component
 * @property string $base_url
 * @property string $path
 * @property string $type
 * @property integer $size
 * @property string $name
 * @property string $upload_ip
 * @property integer $created_at
 * @property string $aliasModel
 */
abstract class FileStorageItem extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'file_storage_item';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['component', 'base_url', 'path'], 'required'],
            [['size', 'created_at'], 'integer'],
            [['component', 'type', 'name'], 'string', 'max' => 255],
            [['base_url', 'path'], 'string', 'max' => 1024],
            [['upload_ip'], 'string', 'max' => 45]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'component' => 'Component',
            'base_url' => 'Base Url',
            'path' => 'Path',
            'type' => 'Type',
            'size' => 'Size',
            'name' => 'Name',
            'upload_ip' => 'Upload Ip',
            'created_at' => 'Created At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\FileStorageItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\FileStorageItemQuery(get_called_class());
    }


}
