<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "history_discount".
 *
 * @property integer $id
 * @property integer $order_id
 * @property integer $code_id
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class HistoryDiscount extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'history_discount';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['order_id', 'code_id', 'status'], 'integer'],
            [['created_at', 'updated_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'order_id' => 'Order ID',
            'code_id' => 'Code ID',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\HistoryDiscountQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\HistoryDiscountQuery(get_called_class());
    }


}
