<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "i18n_source_message".
 *
 * @property integer $id
 * @property string $category
 * @property string $message
 *
 * @property \common\models\I18nMessage[] $i18nMessages
 * @property string $aliasModel
 */
abstract class I18nSourceMessage extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'i18n_source_message';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['message'], 'string'],
            [['category'], 'string', 'max' => 32]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category' => 'Category',
            'message' => 'Message',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getI18nMessages()
    {
        return $this->hasMany(\common\models\I18nMessage::className(), ['id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\I18nSourceMessageQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\I18nSourceMessageQuery(get_called_class());
    }


}
