<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "inventory_receipt_item".
 *
 * @property integer $id
 * @property string $receipt_id
 * @property integer $product_id
 * @property integer $product_variant_id
 * @property integer $quantity
 * @property string $product_serials
 * @property double $unit_price
 * @property double $sub_total_price
 * @property double $total_price
 * @property string $other_cost
 * @property double $total_cost
 * @property double $tax
 * @property string $discount_type
 * @property double $discount_value
 * @property double $total_discount_value
 * @property string $references
 * @property string $note
 * @property integer $owner_id
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $status
 * @property double $tax_price
 * @property string $aliasModel
 */
abstract class InventoryReceiptItem extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'inventory_receipt_item';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['product_id', 'product_variant_id', 'quantity', 'owner_id', 'status'], 'integer'],
            [['product_serials', 'other_cost', 'discount_type', 'references', 'note'], 'string'],
            [['unit_price', 'sub_total_price', 'total_price', 'total_cost', 'tax', 'discount_value', 'total_discount_value', 'tax_price'], 'number'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['receipt_id'], 'string', 'max' => 128]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'receipt_id' => 'Receipt ID',
            'product_id' => 'Product ID',
            'product_variant_id' => 'Product Variant ID',
            'quantity' => 'Quantity',
            'product_serials' => 'Product Serials',
            'unit_price' => 'Unit Price',
            'sub_total_price' => 'Sub Total Price',
            'total_price' => 'Total Price',
            'other_cost' => 'Other Cost',
            'total_cost' => 'Total Cost',
            'tax' => 'Tax',
            'discount_type' => 'Discount Type',
            'discount_value' => 'Discount Value',
            'total_discount_value' => 'Total Discount Value',
            'references' => 'References',
            'note' => 'Note',
            'owner_id' => 'Owner ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'status' => 'Status',
            'tax_price' => 'Tax Price',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\InventoryReceiptItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\InventoryReceiptItemQuery(get_called_class());
    }


}
