<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "inventory_issue".
 *
 * @property integer $id
 * @property string $code
 * @property integer $office_id
 * @property integer $inventory_id
 * @property integer $office_receive_id
 * @property integer $inventory_receive_id
 * @property string $note
 * @property integer $total_number
 * @property integer $created_by
 * @property string $delivery_date
 * @property string $received_date
 * @property string $created_at
 * @property string $progress_status
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $status
 * @property integer $type
 * @property integer $order_id
 * @property string $aliasModel
 */
abstract class InventoryIssue extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'inventory_issue';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['office_id', 'inventory_id', 'office_receive_id', 'inventory_receive_id', 'total_number', 'created_by', 'status', 'type', 'order_id'], 'integer'],
            [['note'], 'string'],
            [['delivery_date', 'received_date', 'created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['code', 'progress_status'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'code' => 'Code',
            'office_id' => 'Office ID',
            'inventory_id' => 'Inventory ID',
            'office_receive_id' => 'Office Receive ID',
            'inventory_receive_id' => 'Inventory Receive ID',
            'note' => 'Note',
            'total_number' => 'Total Number',
            'created_by' => 'Created By',
            'delivery_date' => 'Delivery Date',
            'received_date' => 'Received Date',
            'created_at' => 'Created At',
            'progress_status' => 'Progress Status',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'status' => 'Status',
            'type' => 'Type',
            'order_id' => 'Order ID',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\InventoryIssueQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\InventoryIssueQuery(get_called_class());
    }


}
