<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "inventory_receipt".
 *
 * @property integer $id
 * @property string $code
 * @property integer $office_id
 * @property integer $inventory_id
 * @property integer $supplier_id
 * @property integer $receipt_status
 * @property integer $payment_status
 * @property integer $import_status
 * @property double $total_price
 * @property string $other_cost
 * @property double $total_cost
 * @property string $total_discount_type
 * @property double $total_discount_value
 * @property string $tags
 * @property string $references
 * @property string $note
 * @property string $import_date
 * @property integer $created_by
 * @property integer $priority
 * @property integer $owner_id
 * @property string $group_id
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $status
 * @property string $billing_address
 * @property string $shipping_address
 * @property string $tax
 * @property string $delivery_date
 * @property integer $quantity
 * @property double $sub_total_price
 * @property integer $discount_price
 * @property string $progress_status
 * @property string $aliasModel
 */
abstract class InventoryReceipt extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'inventory_receipt';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['office_id', 'inventory_id', 'supplier_id', 'receipt_status', 'payment_status', 'import_status', 'created_by', 'priority', 'owner_id', 'status', 'quantity', 'discount_price'], 'integer'],
            [['total_price', 'total_cost', 'total_discount_value', 'sub_total_price'], 'number'],
            [['other_cost', 'total_discount_type', 'tags', 'references', 'note', 'group_id', 'billing_address', 'shipping_address', 'progress_status'], 'string'],
            [['import_date', 'created_at', 'updated_at', 'deleted_at', 'delivery_date'], 'safe'],
            [['code'], 'string', 'max' => 128],
            [['tax'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'code' => 'Code',
            'office_id' => 'Office ID',
            'inventory_id' => 'Inventory ID',
            'supplier_id' => 'Supplier ID',
            'receipt_status' => 'Receipt Status',
            'payment_status' => 'Payment Status',
            'import_status' => 'Import Status',
            'total_price' => 'Total Price',
            'other_cost' => 'Other Cost',
            'total_cost' => 'Total Cost',
            'total_discount_type' => 'Total Discount Type',
            'total_discount_value' => 'Total Discount Value',
            'tags' => 'Tags',
            'references' => 'References',
            'note' => 'Note',
            'import_date' => 'Import Date',
            'created_by' => 'Created By',
            'priority' => 'Priority',
            'owner_id' => 'Owner ID',
            'group_id' => 'Group ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'status' => 'Status',
            'billing_address' => 'Billing Address',
            'shipping_address' => 'Shipping Address',
            'tax' => 'Tax',
            'delivery_date' => 'Delivery Date',
            'quantity' => 'Quantity',
            'sub_total_price' => 'Sub Total Price',
            'discount_price' => 'Discount Price',
            'progress_status' => 'Progress Status',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\InventoryReceiptQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\InventoryReceiptQuery(get_called_class());
    }


}
