<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "inventory_issue_item".
 *
 * @property integer $id
 * @property integer $inventory_issue_id
 * @property integer $product_id
 * @property integer $product_variant_id
 * @property integer $number_inventory
 * @property integer $quantity
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $status
 * @property string $aliasModel
 */
abstract class InventoryIssueItem extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'inventory_issue_item';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['inventory_issue_id', 'product_id', 'product_variant_id', 'number_inventory', 'quantity', 'status'], 'integer'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'inventory_issue_id' => 'Inventory Issue ID',
            'product_id' => 'Product ID',
            'product_variant_id' => 'Product Variant ID',
            'number_inventory' => 'Number Inventory',
            'quantity' => 'Quantity',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'status' => 'Status',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\InventoryIssueItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\InventoryIssueItemQuery(get_called_class());
    }


}
