<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "inventory".
 *
 * @property integer $id
 * @property string $name
 * @property string $type
 * @property string $code
 * @property string $description
 * @property integer $office_id
 * @property integer $priority
 * @property integer $parent_id
 * @property integer $owner_id
 * @property string $group_id
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $status
 * @property string $aliasModel
 */
abstract class Inventory extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'inventory';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['description', 'group_id'], 'string'],
            [['office_id', 'priority', 'parent_id', 'owner_id', 'status'], 'integer'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['name'], 'string', 'max' => 256],
            [['type'], 'string', 'max' => 32],
            [['code'], 'string', 'max' => 128]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'type' => 'Type',
            'code' => 'Code',
            'description' => 'Description',
            'office_id' => 'Office ID',
            'priority' => 'Priority',
            'parent_id' => 'Parent ID',
            'owner_id' => 'Owner ID',
            'group_id' => 'Group ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'status' => 'Status',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\InventoryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\InventoryQuery(get_called_class());
    }


}
