<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "inventory_history".
 *
 * @property integer $id
 * @property integer $created_by
 * @property string $action
 * @property string $change_quantity
 * @property integer $inventory
 * @property string $voucher_code
 * @property integer $office_id
 * @property integer $inventory_id
 * @property integer $product_id
 * @property integer $product_variant_id
 * @property string $created_at
 * @property string $updated_at
 * @property integer $status
 * @property string $link_detail
 * @property integer $type
 * @property string $aliasModel
 */
abstract class InventoryHistory extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'inventory_history';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['created_by', 'inventory', 'office_id', 'inventory_id', 'product_id', 'product_variant_id', 'status', 'type'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['action'], 'string', 'max' => 256],
            [['change_quantity', 'voucher_code', 'link_detail'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'created_by' => 'Created By',
            'action' => 'Action',
            'change_quantity' => 'Change Quantity',
            'inventory' => 'Inventory',
            'voucher_code' => 'Voucher Code',
            'office_id' => 'Office ID',
            'inventory_id' => 'Inventory ID',
            'product_id' => 'Product ID',
            'product_variant_id' => 'Product Variant ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'status' => 'Status',
            'link_detail' => 'Link Detail',
            'type' => 'Type',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\InventoryHistoryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\InventoryHistoryQuery(get_called_class());
    }


}
