<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "office".
 *
 * @property integer $id
 * @property string $type
 * @property string $name
 * @property string $description
 * @property string $custom_fields
 * @property string $domains
 * @property string $note
 * @property string $postal_code
 * @property string $health_score
 * @property string $account_tier
 * @property string $renewal_date
 * @property string $industry
 * @property string $work_phone
 * @property string $address1
 * @property string $address2
 * @property string $province_code
 * @property string $district_code
 * @property string $ward_code
 * @property string $country
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $status
 * @property string $email
 * @property string $street
 * @property integer $contact_person_id
 * @property string $biz_phone
 * @property string $security_code
 * @property string $additional_information
 * @property double $latitude
 * @property double $longitude
 * @property string $aliasModel
 */
abstract class Office extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'office';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['custom_fields', 'note', 'additional_information'], 'string'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['status', 'contact_person_id'], 'integer'],
            [['latitude', 'longitude'], 'number'],
            [['type', 'name', 'domains', 'postal_code', 'health_score', 'account_tier', 'renewal_date', 'industry', 'ward_code', 'email', 'street'], 'string', 'max' => 255],
            [['description', 'work_phone', 'address1', 'address2', 'province_code', 'district_code', 'country', 'biz_phone', 'security_code'], 'string', 'max' => 512]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Type',
            'name' => 'Name',
            'description' => 'Description',
            'custom_fields' => 'Custom Fields',
            'domains' => 'Domains',
            'note' => 'Note',
            'postal_code' => 'Postal Code',
            'health_score' => 'Health Score',
            'account_tier' => 'Account Tier',
            'renewal_date' => 'Renewal Date',
            'industry' => 'Industry',
            'work_phone' => 'Work Phone',
            'address1' => 'Address 1',
            'address2' => 'Address 2',
            'province_code' => 'Province Code',
            'district_code' => 'District Code',
            'ward_code' => 'Ward Code',
            'country' => 'Country',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'status' => 'Status',
            'email' => 'Email',
            'street' => 'Street',
            'contact_person_id' => 'Contact Person ID',
            'biz_phone' => 'Biz Phone',
            'security_code' => 'Security Code',
            'additional_information' => 'Additional Information',
            'latitude' => 'Latitude',
            'longitude' => 'Longitude',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\OfficeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\OfficeQuery(get_called_class());
    }


}
