<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "order_ship".
 *
 * @property integer $id
 * @property integer $order_id
 * @property string $sender_name
 * @property string $sender_province_id
 * @property string $sender_district_id
 * @property string $sender_ward_id
 * @property string $sender_address
 * @property string $sender_phone
 * @property string $sender_email
 * @property string $order_code
 * @property string $receiver_name
 * @property string $receiver_province_id
 * @property string $receiver_district_id
 * @property string $receiver_ward_id
 * @property string $receiver_address
 * @property string $receiver_phone
 * @property string $receiver_email
 * @property integer $status
 * @property double $cod
 * @property integer $payment_type_id
 * @property string $note
 * @property double $value
 * @property string $shipper_note
 * @property double $weight
 * @property double $length
 * @property double $width
 * @property double $height
 * @property string $coupon
 * @property string $transport
 * @property string $pick_shift
 * @property string $extra_fields
 * @property string $extra_shipper
 * @property string $weight_option
 * @property string $shipper_type
 * @property integer $shipper_id
 * @property string $expected_delivery_time
 * @property string $partner_code
 * @property double $fee
 * @property double $total_fee
 * @property string $created_at
 * @property string $updated_at
 * @property string $progress_status
 * @property string $aliasModel
 */
abstract class OrderShip extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order_ship';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['order_id', 'status', 'payment_type_id', 'shipper_id'], 'integer'],
            [['cod', 'value', 'weight', 'length', 'width', 'height', 'fee', 'total_fee'], 'number'],
            [['note', 'shipper_note', 'extra_fields', 'extra_shipper', 'progress_status'], 'string'],
            [['expected_delivery_time', 'created_at', 'updated_at'], 'safe'],
            [['sender_name', 'sender_province_id', 'sender_district_id', 'sender_ward_id', 'sender_phone', 'sender_email', 'order_code', 'receiver_name', 'receiver_province_id', 'receiver_district_id', 'receiver_ward_id', 'receiver_phone', 'receiver_email', 'coupon', 'transport', 'pick_shift', 'weight_option', 'shipper_type', 'partner_code'], 'string', 'max' => 255],
            [['sender_address', 'receiver_address'], 'string', 'max' => 500]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'order_id' => 'Order ID',
            'sender_name' => 'Sender Name',
            'sender_province_id' => 'Sender Province ID',
            'sender_district_id' => 'Sender District ID',
            'sender_ward_id' => 'Sender Ward ID',
            'sender_address' => 'Sender Address',
            'sender_phone' => 'Sender Phone',
            'sender_email' => 'Sender Email',
            'order_code' => 'Order Code',
            'receiver_name' => 'Receiver Name',
            'receiver_province_id' => 'Receiver Province ID',
            'receiver_district_id' => 'Receiver District ID',
            'receiver_ward_id' => 'Receiver Ward ID',
            'receiver_address' => 'Receiver Address',
            'receiver_phone' => 'Receiver Phone',
            'receiver_email' => 'Receiver Email',
            'status' => 'Status',
            'cod' => 'Cod',
            'payment_type_id' => 'Payment Type ID',
            'note' => 'Note',
            'value' => 'Value',
            'shipper_note' => 'Shipper Note',
            'weight' => 'Weight',
            'length' => 'Length',
            'width' => 'Width',
            'height' => 'Height',
            'coupon' => 'Coupon',
            'transport' => 'Transport',
            'pick_shift' => 'Pick Shift',
            'extra_fields' => 'Extra Fields',
            'extra_shipper' => 'Extra Shipper',
            'weight_option' => 'Weight Option',
            'shipper_type' => 'Shipper Type',
            'shipper_id' => 'Shipper ID',
            'expected_delivery_time' => 'Expected Delivery Time',
            'partner_code' => 'Partner Code',
            'fee' => 'Fee',
            'total_fee' => 'Total Fee',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'progress_status' => 'Progress Status',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\OrderShipQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\OrderShipQuery(get_called_class());
    }


}
