<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "order".
 *
 * @property integer $id
 * @property integer $office_id
 * @property integer $inventory_id
 * @property integer $client_id
 * @property string $price_policy
 * @property string $tax
 * @property string $shipping_address
 * @property string $order_address
 * @property string $note
 * @property string $return_note
 * @property string $tags
 * @property double $total_price
 * @property double $tax_price
 * @property double $discount
 * @property double $delivery_fee
 * @property double $payments
 * @property string $delivery
 * @property integer $created_by
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $status
 * @property string $data_tax
 * @property string $data_discount
 * @property string $data_delivery_fee
 * @property string $code
 * @property string $channel
 * @property integer $quantity
 * @property string $data_payments
 * @property integer $promotion_id
 * @property string $progress_status
 * @property integer $type
 * @property string $aliasModel
 */
abstract class Order extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['office_id', 'inventory_id', 'client_id', 'created_by', 'status', 'quantity', 'promotion_id', 'type'], 'integer'],
            [['shipping_address', 'order_address', 'note', 'return_note', 'tags', 'delivery', 'data_tax', 'data_discount', 'data_delivery_fee', 'data_payments'], 'string'],
            [['total_price', 'tax_price', 'discount', 'delivery_fee', 'payments'], 'number'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['price_policy', 'tax', 'code', 'channel', 'progress_status'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'office_id' => 'Office ID',
            'inventory_id' => 'Inventory ID',
            'client_id' => 'Client ID',
            'price_policy' => 'Price Policy',
            'tax' => 'Tax',
            'shipping_address' => 'Shipping Address',
            'order_address' => 'Order Address',
            'note' => 'Note',
            'return_note' => 'Return Note',
            'tags' => 'Tags',
            'total_price' => 'Total Price',
            'tax_price' => 'Tax Price',
            'discount' => 'Discount',
            'delivery_fee' => 'Delivery Fee',
            'payments' => 'Payments',
            'delivery' => 'Delivery',
            'created_by' => 'Created By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'status' => 'Status',
            'data_tax' => 'Data Tax',
            'data_discount' => 'Data Discount',
            'data_delivery_fee' => 'Data Delivery Fee',
            'code' => 'Code',
            'channel' => 'Channel',
            'quantity' => 'Quantity',
            'data_payments' => 'Data Payments',
            'promotion_id' => 'Promotion ID',
            'progress_status' => 'Progress Status',
            'type' => 'Type',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\OrderQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\OrderQuery(get_called_class());
    }


}
