<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "page".
 *
 * @property integer $id
 * @property string $slug
 * @property string $title
 * @property integer $status
 * @property string $content
 * @property integer $create_by
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class Page extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'page';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status', 'create_by'], 'integer'],
            [['content'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['slug', 'title'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'slug' => 'Slug',
            'title' => 'Title',
            'status' => 'Status',
            'content' => 'Content',
            'create_by' => 'Create By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\PageQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\PageQuery(get_called_class());
    }


}
