<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "posts".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $post_title
 * @property integer $category_id
 * @property string $post_slug
 * @property integer $status
 * @property string $publish_at
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property string $post_content
 * @property string $aliasModel
 */
abstract class Post extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'posts';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'category_id', 'status'], 'integer'],
            [['publish_at', 'created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['post_content'], 'string'],
            [['post_title', 'post_slug'], 'string', 'max' => 500]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'post_title' => 'Post Title',
            'category_id' => 'Category ID',
            'post_slug' => 'Post Slug',
            'status' => 'Status',
            'publish_at' => 'Publish At',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'post_content' => 'Post Content',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\PostQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\PostQuery(get_called_class());
    }


}
