<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "products".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $product_title
 * @property string $product_content
 * @property integer $category_id
 * @property string $product_slug
 * @property string $product_excerpt
 * @property string $images
 * @property double $price
 * @property double $old_price
 * @property integer $status
 * @property string $publish_at
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property string $aliasModel
 */
abstract class Product extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'products';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'category_id', 'status'], 'integer'],
            [['product_content', 'product_excerpt', 'images'], 'string'],
            [['price', 'old_price'], 'number'],
            [['publish_at', 'created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['product_title', 'product_slug'], 'string', 'max' => 500]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'product_title' => 'Product Title',
            'product_content' => 'Product Content',
            'category_id' => 'Category ID',
            'product_slug' => 'Product Slug',
            'product_excerpt' => 'Product Excerpt',
            'images' => 'Images',
            'price' => 'Price',
            'old_price' => 'Old Price',
            'status' => 'Status',
            'publish_at' => 'Publish At',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\ProductQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\ProductQuery(get_called_class());
    }


}
