<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "product_properties".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $product_id
 * @property integer $property_id
 * @property string $property_value
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property string $aliasModel
 */
abstract class ProductProperty extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_properties';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'product_id', 'property_id'], 'integer'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['property_value'], 'string', 'max' => 500]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'product_id' => 'Product ID',
            'property_id' => 'Property ID',
            'property_value' => 'Property Value',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\ProductPropertyQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\ProductPropertyQuery(get_called_class());
    }


}
