<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "product_asset".
 *
 * @property integer $id
 * @property integer $type
 * @property string $src
 * @property integer $product_id
 * @property string $product_variant_ids
 * @property string $group_id
 * @property integer $priority
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $status
 * @property string $aliasModel
 */
abstract class ProductAsset extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_asset';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'product_id', 'priority', 'status'], 'integer'],
            [['src', 'product_variant_ids', 'group_id'], 'string'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Type',
            'src' => 'Src',
            'product_id' => 'Product ID',
            'product_variant_ids' => 'Product Variant Ids',
            'group_id' => 'Group ID',
            'priority' => 'Priority',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'status' => 'Status',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\ProductAssetQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\ProductAssetQuery(get_called_class());
    }


}
