<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "product_inventory".
 *
 * @property integer $id
 * @property integer $product_id
 * @property integer $product_variant_id
 * @property integer $inventory_id
 * @property integer $quantity
 * @property double $prime_cost
 * @property double $unit_price
 * @property string $policy
 * @property integer $priority
 * @property integer $owner_id
 * @property string $group_id
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $status
 * @property integer $sll_price
 * @property integer $incoming
 * @property integer $on_way
 * @property integer $committed
 * @property integer $available
 * @property string $aliasModel
 */
abstract class ProductInventory extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_inventory';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['product_id', 'product_variant_id', 'inventory_id', 'quantity', 'priority', 'owner_id', 'status', 'sll_price', 'incoming', 'on_way', 'committed', 'available'], 'integer'],
            [['prime_cost', 'unit_price'], 'number'],
            [['policy', 'group_id'], 'string'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'product_id' => 'Product ID',
            'product_variant_id' => 'Product Variant ID',
            'inventory_id' => 'Inventory ID',
            'quantity' => 'Quantity',
            'prime_cost' => 'Prime Cost',
            'unit_price' => 'Unit Price',
            'policy' => 'Policy',
            'priority' => 'Priority',
            'owner_id' => 'Owner ID',
            'group_id' => 'Group ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'status' => 'Status',
            'sll_price' => 'Sll Price',
            'incoming' => 'Incoming',
            'on_way' => 'On Way',
            'committed' => 'Committed',
            'available' => 'Available',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\ProductInventoryQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\ProductInventoryQuery(get_called_class());
    }


}
