<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "product_property".
 *
 * @property integer $id
 * @property integer $product_id
 * @property integer $product_variant_id
 * @property string $property_content
 * @property integer $type
 * @property integer $parent_id
 * @property integer $group_id
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class ProductProperty extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_property';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['product_id', 'product_variant_id', 'type', 'parent_id', 'group_id'], 'integer'],
            [['property_content'], 'string'],
            [['created_at', 'updated_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'product_id' => 'Product ID',
            'product_variant_id' => 'Product Variant ID',
            'property_content' => 'Property Content',
            'type' => 'Type',
            'parent_id' => 'Parent ID',
            'group_id' => 'Group ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\ProductPropertyQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\ProductPropertyQuery(get_called_class());
    }


}
