<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "product".
 *
 * @property integer $id
 * @property string $name
 * @property string $type
 * @property string $key
 * @property integer $code_id
 * @property string $sku
 * @property string $bar_code
 * @property integer $category_id
 * @property integer $brand_id
 * @property string $slug
 * @property string $note
 * @property string $icon
 * @property string $images
 * @property string $custom_price
 * @property double $unit_price
 * @property double $sll_price
 * @property double $import_price
 * @property string $product_options
 * @property string $product_modifier
 * @property string $color
 * @property integer $has_tax
 * @property integer $has_inventory
 * @property integer $has_properties
 * @property string $dimension
 * @property string $tags
 * @property integer $allow_sell
 * @property string $weight
 * @property string $weight_type
 * @property integer $priority
 * @property string $short_description
 * @property string $description
 * @property string $warranty_description
 * @property string $product_period
 * @property integer $prepare_duration
 * @property integer $parent_id
 * @property integer $owner_id
 * @property string $group_id
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $visible
 * @property string $supplier_ids
 * @property string $product_status
 * @property integer $status
 * @property string $aliasModel
 */
abstract class Product extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['code_id', 'category_id', 'brand_id', 'has_tax', 'has_inventory', 'has_properties', 'allow_sell', 'priority', 'prepare_duration', 'parent_id', 'owner_id', 'visible', 'status'], 'integer'],
            [['slug', 'note', 'icon', 'images', 'custom_price', 'product_options', 'product_modifier', 'short_description', 'description', 'warranty_description', 'product_period', 'group_id', 'supplier_ids'], 'string'],
            [['unit_price', 'sll_price', 'import_price'], 'number'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['name'], 'string', 'max' => 256],
            [['type', 'product_status'], 'string', 'max' => 32],
            [['key', 'bar_code'], 'string', 'max' => 128],
            [['sku', 'dimension'], 'string', 'max' => 64],
            [['color'], 'string', 'max' => 10],
            [['tags', 'weight', 'weight_type'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'type' => 'Type',
            'key' => 'Key',
            'code_id' => 'Code ID',
            'sku' => 'Sku',
            'bar_code' => 'Bar Code',
            'category_id' => 'Category ID',
            'brand_id' => 'Brand ID',
            'slug' => 'Slug',
            'note' => 'Note',
            'icon' => 'Icon',
            'images' => 'Images',
            'custom_price' => 'Custom Price',
            'unit_price' => 'Unit Price',
            'sll_price' => 'Sll Price',
            'import_price' => 'Import Price',
            'product_options' => 'Product Options',
            'product_modifier' => 'Product Modifier',
            'color' => 'Color',
            'has_tax' => 'Has Tax',
            'has_inventory' => 'Has Inventory',
            'has_properties' => 'Has Properties',
            'dimension' => 'Dimension',
            'tags' => 'Tags',
            'allow_sell' => 'Allow Sell',
            'weight' => 'Weight',
            'weight_type' => 'Weight Type',
            'priority' => 'Priority',
            'short_description' => 'Short Description',
            'description' => 'Description',
            'warranty_description' => 'Warranty Description',
            'product_period' => 'Product Period',
            'prepare_duration' => 'Prepare Duration',
            'parent_id' => 'Parent ID',
            'owner_id' => 'Owner ID',
            'group_id' => 'Group ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'visible' => 'Visible',
            'supplier_ids' => 'Supplier Ids',
            'product_status' => 'Product Status',
            'status' => 'Status',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\ProductQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\ProductQuery(get_called_class());
    }


}
