<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "product_meta".
 *
 * @property integer $id
 * @property integer $product_id
 * @property string $warranty
 * @property string $installment
 * @property string $aliasModel
 */
abstract class ProductMetum extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_meta';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['product_id'], 'integer'],
            [['warranty', 'installment'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'product_id' => 'Product ID',
            'warranty' => 'Warranty',
            'installment' => 'Installment',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\ProductMetumQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\ProductMetumQuery(get_called_class());
    }


}
