<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "promotion".
 *
 * @property integer $id
 * @property string $title
 * @property string $code
 * @property string $description
 * @property integer $discount_type
 * @property double $discount_value
 * @property string $start_date
 * @property string $end_date
 * @property integer $limit
 * @property integer $used
 * @property double $order_total_required
 * @property string $group_customers
 * @property integer $status
 * @property string $office_ids
 * @property string $condition_items
 * @property string $condition_type
 * @property integer $promotion_type
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property string $offices
 * @property string $aliasModel
 */
abstract class Promotion extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'promotion';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['description', 'group_customers', 'office_ids', 'condition_items', 'condition_type', 'offices'], 'string'],
            [['discount_type', 'limit', 'used', 'status', 'promotion_type'], 'integer'],
            [['discount_value', 'order_total_required'], 'number'],
            [['start_date', 'end_date', 'created_at', 'updated_at'], 'safe'],
            [['title', 'code', 'deleted_at'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'code' => 'Code',
            'description' => 'Description',
            'discount_type' => 'Discount Type',
            'discount_value' => 'Discount Value',
            'start_date' => 'Start Date',
            'end_date' => 'End Date',
            'limit' => 'Limit',
            'used' => 'Used',
            'order_total_required' => 'Order Total Required',
            'group_customers' => 'Group Customers',
            'status' => 'Status',
            'office_ids' => 'Office Ids',
            'condition_items' => 'Condition Items',
            'condition_type' => 'Condition Type',
            'promotion_type' => 'Promotion Type',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'offices' => 'Offices',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\PromotionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\PromotionQuery(get_called_class());
    }


}
