<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "property".
 *
 * @property integer $id
 * @property string $property_title
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class Property extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'property';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['property_title'], 'string'],
            [['created_at', 'updated_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'property_title' => 'Property Title',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\PropertyQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\PropertyQuery(get_called_class());
    }


}
