<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "shipper".
 *
 * @property integer $id
 * @property string $name
 * @property string $short_name
 * @property string $slug
 * @property string $type
 * @property string $thumbnail
 * @property string $token
 * @property string $service_extras
 * @property integer $status
 * @property integer $created_by
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property string $aliasModel
 */
abstract class Shipper extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'shipper';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'service_extras'], 'string'],
            [['status', 'created_by'], 'integer'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['name', 'short_name', 'slug', 'thumbnail'], 'string', 'max' => 255],
            [['token'], 'string', 'max' => 500]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'short_name' => 'Short Name',
            'slug' => 'Slug',
            'type' => 'Type',
            'thumbnail' => 'Thumbnail',
            'token' => 'Token',
            'service_extras' => 'Service Extras',
            'status' => 'Status',
            'created_by' => 'Created By',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\ShipperQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\ShipperQuery(get_called_class());
    }


}
