<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "sliders".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $image
 * @property string $link_to
 * @property integer $status
 * @property integer $priority
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property string $aliasModel
 */
abstract class Slider extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sliders';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'status', 'priority'], 'integer'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['image', 'link_to'], 'string', 'max' => 500]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'image' => 'Image',
            'link_to' => 'Link To',
            'status' => 'Status',
            'priority' => 'Priority',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\SliderQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\SliderQuery(get_called_class());
    }


}
