<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "states".
 *
 * @property integer $id
 * @property string $name
 * @property integer $country_id
 * @property string $created_at
 * @property string $updated_at
 * @property integer $flag
 * @property string $aliasModel
 */
abstract class State extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'states';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'country_id'], 'required'],
            [['country_id', 'flag'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'country_id' => 'Country ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'flag' => 'Flag',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\StateQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\StateQuery(get_called_class());
    }


}
