<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "stocktaking".
 *
 * @property integer $id
 * @property string $code
 * @property integer $office_id
 * @property integer $inventory_id
 * @property string $note
 * @property string $tags
 * @property integer $total_difference
 * @property integer $total_adjustment
 * @property integer $created_by
 * @property string $stocktaking_date
 * @property string $progress_status
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $status
 * @property string $aliasModel
 */
abstract class Stocktaking extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'stocktaking';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['office_id', 'inventory_id', 'total_difference', 'total_adjustment', 'created_by', 'status'], 'integer'],
            [['note', 'tags'], 'string'],
            [['stocktaking_date', 'created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['code', 'progress_status'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'code' => 'Code',
            'office_id' => 'Office ID',
            'inventory_id' => 'Inventory ID',
            'note' => 'Note',
            'tags' => 'Tags',
            'total_difference' => 'Total Difference',
            'total_adjustment' => 'Total Adjustment',
            'created_by' => 'Created By',
            'stocktaking_date' => 'Stocktaking Date',
            'progress_status' => 'Progress Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'status' => 'Status',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\StocktakingQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\StocktakingQuery(get_called_class());
    }


}
