<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "stocktaking_item".
 *
 * @property integer $id
 * @property integer $stocktaking_id
 * @property integer $product_id
 * @property integer $product_variant_id
 * @property integer $number_inventory
 * @property integer $number_difference
 * @property integer $number_adjustment
 * @property string $reason
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $status
 * @property string $aliasModel
 */
abstract class StocktakingItem extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'stocktaking_item';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['stocktaking_id', 'product_id', 'product_variant_id', 'number_inventory', 'number_difference', 'number_adjustment', 'status'], 'integer'],
            [['reason'], 'string'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'stocktaking_id' => 'Stocktaking ID',
            'product_id' => 'Product ID',
            'product_variant_id' => 'Product Variant ID',
            'number_inventory' => 'Number Inventory',
            'number_difference' => 'Number Difference',
            'number_adjustment' => 'Number Adjustment',
            'reason' => 'Reason',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'status' => 'Status',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\StocktakingItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\StocktakingItemQuery(get_called_class());
    }


}
