<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "street".
 *
 * @property integer $id
 * @property string $_name
 * @property string $_prefix
 * @property integer $_province_id
 * @property integer $_district_id
 * @property string $aliasModel
 */
abstract class Street extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'street';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['_province_id', '_district_id'], 'integer'],
            [['_name'], 'string', 'max' => 100],
            [['_prefix'], 'string', 'max' => 20]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            '_name' => 'Name',
            '_prefix' => 'Prefix',
            '_province_id' => 'Province ID',
            '_district_id' => 'District ID',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\StreetQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\StreetQuery(get_called_class());
    }


}
