<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "supplier".
 *
 * @property integer $id
 * @property string $name
 * @property string $type
 * @property string $code
 * @property string $description
 * @property string $icon
 * @property string $images
 * @property string $color
 * @property string $email
 * @property string $phone
 * @property string $website
 * @property string $fax
 * @property string $tax_code
 * @property string $address_1
 * @property string $address_2
 * @property integer $contact_id
 * @property string $note
 * @property string $supplier_status
 * @property integer $priority
 * @property integer $parent_id
 * @property integer $owner_id
 * @property string $group_id
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $status
 * @property string $aliasModel
 */
abstract class Supplier extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'supplier';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['description', 'icon', 'images', 'address_1', 'address_2', 'note', 'group_id'], 'string'],
            [['contact_id', 'priority', 'parent_id', 'owner_id', 'status'], 'integer'],
            [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['name'], 'string', 'max' => 256],
            [['type'], 'string', 'max' => 32],
            [['code', 'email', 'website'], 'string', 'max' => 128],
            [['color'], 'string', 'max' => 10],
            [['phone', 'fax', 'tax_code', 'supplier_status'], 'string', 'max' => 64]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'type' => 'Type',
            'code' => 'Code',
            'description' => 'Description',
            'icon' => 'Icon',
            'images' => 'Images',
            'color' => 'Color',
            'email' => 'Email',
            'phone' => 'Phone',
            'website' => 'Website',
            'fax' => 'Fax',
            'tax_code' => 'Tax Code',
            'address_1' => 'Address  1',
            'address_2' => 'Address  2',
            'contact_id' => 'Contact ID',
            'note' => 'Note',
            'supplier_status' => 'Supplier Status',
            'priority' => 'Priority',
            'parent_id' => 'Parent ID',
            'owner_id' => 'Owner ID',
            'group_id' => 'Group ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'status' => 'Status',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\SupplierQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\SupplierQuery(get_called_class());
    }


}
