<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "timezone".
 *
 * @property integer $id
 * @property string $timezone
 * @property string $label
 * @property string $offset
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class Timezone extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'timezone';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['created_at', 'updated_at'], 'integer'],
            [['timezone', 'label', 'offset'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'timezone' => 'Timezone',
            'label' => 'Label',
            'offset' => 'Offset',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'created_at' => 'Created at',
            'updated_at' => 'Updated at',
        ]);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\TimezoneQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\TimezoneQuery(get_called_class());
    }


}
