<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "user_supplier".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $supplier_id
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class UserSupplier extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user_supplier';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'supplier_id', 'status'], 'integer'],
            [['created_at', 'updated_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'supplier_id' => 'Supplier ID',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\UserSupplierQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\UserSupplierQuery(get_called_class());
    }


}
