<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "ward".
 *
 * @property string $code
 * @property string $code_ghn
 * @property string $name
 * @property string $name_en
 * @property string $full_name
 * @property string $full_name_en
 * @property string $code_name
 * @property string $district_code
 * @property integer $administrative_unit_id
 *
 * @property \common\models\AdministrativeUnit $administrativeUnit
 * @property \common\models\District $districtCode
 * @property string $aliasModel
 */
abstract class Ward extends \common\models\base\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ward';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['code', 'name'], 'required'],
            [['administrative_unit_id'], 'integer'],
            [['code', 'district_code'], 'string', 'max' => 20],
            [['code_ghn', 'name', 'name_en', 'full_name', 'full_name_en', 'code_name'], 'string', 'max' => 255],
            [['code'], 'unique'],
            [['administrative_unit_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\AdministrativeUnit::className(), 'targetAttribute' => ['administrative_unit_id' => 'id']],
            [['district_code'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\District::className(), 'targetAttribute' => ['district_code' => 'code']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'code' => 'Code',
            'code_ghn' => 'Code Ghn',
            'name' => 'Name',
            'name_en' => 'Name En',
            'full_name' => 'Full Name',
            'full_name_en' => 'Full Name En',
            'code_name' => 'Code Name',
            'district_code' => 'District Code',
            'administrative_unit_id' => 'Administrative Unit ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAdministrativeUnit()
    {
        return $this->hasOne(\common\models\AdministrativeUnit::className(), ['id' => 'administrative_unit_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistrictCode()
    {
        return $this->hasOne(\common\models\District::className(), ['code' => 'district_code']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\WardQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\WardQuery(get_called_class());
    }


}
