<?php

namespace console\controllers;

use Yii;
use yii\base\InvalidConfigException;
use yii\console\Controller;
use yii\db\Connection;
use yii\db\Query;

class SyncDatabaseController extends Controller
{

    /**
     * @throws InvalidConfigException
     */
    public function beforeAction($action)
    {
        Yii::$app->set("db_wp", [
            'class' => Connection::className(),
            'dsn' => env('DB_DSN_SYNC'),
            'username' => env('DB_USERNAME'),
            'password' => env('DB_PASSWORD'),
            'tablePrefix' => env('DB_TABLE_PREFIX'),
            'charset' => env('DB_CHARSET', 'utf8'),
            'enableSchemaCache' => YII_ENV_PROD,
        ]);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionRun()
    {

    }


}